version: "3.9"

services:
  whisper-hailo:
    image: whisper-hailo-image:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      IS_HAILO_ON_DEVICE: "TRUE"
      HAILO_VERSION: "HAILO8L"         # HAILO8 or HAILO8L
    ports:
      - "10300:10300"
    volumes:
      - /dev:/dev
      - /lib/firmware:/lib/firmware
      - /lib/udev/rules.d:/lib/udev/rules.d
      - /lib/modules:/lib/modules 
    devices:
      - /dev/hailo0:/dev/hailo0
    command:
      - "poetry"
      - "run"
      - "uvicorn"
      - "main:app"
      - "--port"
      - "10300"
      - "--host"
      - "0.0.0.0"
      - "--log-config"
      - "infrastructure/config/logging_config.json"